# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Manual Test CI

on: workflow_dispatch

    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Test ssh copying files
      - name: Copying files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ""
          rm: true
          source: "dist/"
          target: "/home/${{ secrets.SSH_USER }}/temporary_test/"
